server:
  port: 8123
  servlet:
    context-path: /api

spring:
  application:
    name: yu-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_picture
    username: "用户名"
    password: "密码"

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete  // 逻辑删除字段
      logic-not-delete-value: 0     // 0 没删除
      logic-delete-value: 1         // 1 删除

#接口文档
knife4j:
  enable: true
  openapi:
    title: doc
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.xiaob.yupicturebackend.controller